# SPDX-License-Identifier: Apache-2.0
"""Standalone inference for split-input YAMNet FP32 / INT16 TFLite models.

This script runs inference on one audio clip or a directory of WAV files using
the split mel-patch YAMNet models generated by download_model.py.

Usage:
    python inference.py path/to/audio.wav
    python inference.py --audio-dir eval_audio --model Model/yamnet_INT16.tflite
    python inference.py sample.wav --top-k 10
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path
from typing import List, Tuple

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")

import numpy as np
import tensorflow as tf

try:
    from tqdm import tqdm
except Exception:
    tqdm = None

tf.get_logger().setLevel("ERROR")

BASE_DIR = Path(__file__).resolve().parent
YAMNET_SRC = BASE_DIR / "utils"
if str(YAMNET_SRC) not in sys.path:
    sys.path.insert(0, str(YAMNET_SRC))

import features as features_mod  # noqa: E402
import params as params_mod  # noqa: E402

MODEL_PATH = BASE_DIR / "model" / "yamnet_FP32.tflite"
CLASS_MAP_PATH = BASE_DIR / "model" / "yamnet_class_map.csv"
DEFAULT_AUDIO_DIR = BASE_DIR / "eval_audio"

SAMPLE_RATE = 16000
NUM_CLASSES = 521
TOP_K = 5


def load_wav(audio_path: Path, target_sr: int = SAMPLE_RATE) -> np.ndarray:
    try:
        import scipy.io.wavfile as wavfile

        sr, data = wavfile.read(str(audio_path))
        if data.dtype == np.int16:
            wave = data.astype(np.float32) / 32768.0
        elif data.dtype == np.int32:
            wave = data.astype(np.float32) / 2147483648.0
        elif data.dtype == np.float32:
            wave = np.clip(data, -1.0, 1.0)
        else:
            wave = data.astype(np.float32)

        if wave.ndim > 1:
            wave = wave.mean(axis=1)

        if sr != target_sr:
            try:
                import resampy

                wave = resampy.resample(wave, sr, target_sr)
            except ImportError:
                new_len = int(len(wave) * target_sr / sr)
                wave = np.interp(
                    np.linspace(0, len(wave), new_len, endpoint=False),
                    np.arange(len(wave)),
                    wave,
                ).astype(np.float32)
        return wave.astype(np.float32)
    except Exception:
        import librosa

        wave, _ = librosa.load(str(audio_path), sr=target_sr, mono=True)
        return wave.astype(np.float32)


def load_labels(class_map_path: Path) -> List[str]:
    labels: List[str] = []
    with open(class_map_path, newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        next(reader)
        for row in reader:
            labels.append(row[2])
    if len(labels) != NUM_CLASSES:
        raise RuntimeError(f"Expected {NUM_CLASSES} labels, got {len(labels)}")
    return labels


def wav_to_patches(waveform: np.ndarray) -> np.ndarray:
    params_obj = params_mod.Params(sample_rate=SAMPLE_RATE, patch_hop_seconds=0.48)
    _spec, patches = features_mod.waveform_to_log_mel_spectrogram_patches(
        tf.constant(waveform, dtype=tf.float32), params_obj
    )
    return patches.numpy().astype(np.float32)


class YamnetTFLite:
    def __init__(self, model_path: Path):
        self.interpreter = tf.lite.Interpreter(model_path=str(model_path), num_threads=4)
        self.interpreter.allocate_tensors()
        self.in_det = self.interpreter.get_input_details()[0]
        self.out_det = self.interpreter.get_output_details()[0]
        self.in_dtype = self.in_det["dtype"]
        self.out_dtype = self.out_det["dtype"]
        self.in_scale, self.in_zp = self.in_det["quantization"]
        self.out_scale, self.out_zp = self.out_det["quantization"]

        if list(self.in_det["shape"]) != [1, 96, 64]:
            raise RuntimeError(f"Unexpected input shape: {self.in_det['shape']}")
        if self.in_dtype not in (np.float32, np.int16):
            raise RuntimeError(f"Unsupported input dtype: {self.in_dtype}")
        if self.out_dtype not in (np.float32, np.int16):
            raise RuntimeError(f"Unsupported output dtype: {self.out_dtype}")

    def score_patches(self, patches: np.ndarray) -> np.ndarray:
        scores = np.empty((patches.shape[0], NUM_CLASSES), dtype=np.float32)
        for idx in range(patches.shape[0]):
            patch = patches[idx]
            if self.in_dtype == np.float32:
                tensor = patch[np.newaxis, ...].astype(np.float32)
            else:
                tensor = np.round(patch / self.in_scale + self.in_zp)
                tensor = np.clip(tensor, -32768, 32767).astype(np.int16)
                tensor = tensor[np.newaxis, ...]

            self.interpreter.set_tensor(self.in_det["index"], tensor)
            self.interpreter.invoke()
            raw = self.interpreter.get_tensor(self.out_det["index"])[0]
            if self.out_dtype == np.float32:
                scores[idx] = raw.astype(np.float32)
            else:
                scores[idx] = (raw.astype(np.float32) - self.out_zp) * self.out_scale
        return scores


def top_k(scores: np.ndarray, labels: List[str], k: int) -> List[Tuple[int, str, float]]:
    peak = np.max(scores, axis=0)
    indices = np.argsort(peak)[-k:][::-1]
    return [(int(i), labels[int(i)], float(peak[int(i)])) for i in indices]


def infer_file(audio_path: Path, model: YamnetTFLite, labels: List[str], top_k_num: int) -> List[Tuple[int, str, float]]:
    waveform = load_wav(audio_path)
    min_samples = int(SAMPLE_RATE * 1.05)
    if len(waveform) < min_samples:
        waveform = np.pad(waveform, (0, min_samples - len(waveform)))
    patches = wav_to_patches(waveform)
    if patches.shape[0] == 0:
        raise RuntimeError(f"No patches generated for {audio_path}")
    scores = model.score_patches(patches)
    return top_k(scores, labels, top_k_num)


def print_predictions(audio_path: Path, preds: List[Tuple[int, str, float]]) -> None:
    print(f"\n{audio_path}")
    print("-" * 60)
    print(f"{'Rank':<5}{'Idx':<6}{'Label':<38}{'Score':>8}")
    print("-" * 60)
    for rank, (idx, label, score) in enumerate(preds, 1):
        print(f"{rank:<5}{idx:<6}{label:<38}{score:>8.4f}")
    print("-" * 60)


def main() -> int:
    parser = argparse.ArgumentParser(description="Standalone inference for split-input YAMNet TFLite models.")
    parser.add_argument("audio", nargs="?", default=None, help="Path to one audio file")
    parser.add_argument("--audio-dir", default=None, help="Directory of WAV files")
    parser.add_argument("--model", default=str(MODEL_PATH), help=f"Model path (default: {MODEL_PATH})")
    parser.add_argument("--class-map", default=str(CLASS_MAP_PATH), help=f"Class map CSV (default: {CLASS_MAP_PATH})")
    parser.add_argument("--top-k", type=int, default=TOP_K, help=f"Top-K predictions (default: {TOP_K})")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of files in --audio-dir mode")
    args = parser.parse_args()

    model_path = Path(args.model)
    class_map_path = Path(args.class_map)
    if not model_path.is_file():
        print(f"[ERROR] model not found: {model_path}", file=sys.stderr)
        return 2
    if not class_map_path.is_file():
        print(f"[ERROR] class map not found: {class_map_path}", file=sys.stderr)
        return 2

    if args.audio:
        audio_paths = [Path(args.audio)]
    elif args.audio_dir:
        audio_paths = sorted(Path(args.audio_dir).glob("*.wav"))
    else:
        audio_paths = sorted(DEFAULT_AUDIO_DIR.glob("*.wav"))

    if args.limit is not None:
        audio_paths = audio_paths[: args.limit]
    if not audio_paths:
        print("[ERROR] no audio files found", file=sys.stderr)
        return 2

    labels = load_labels(class_map_path)
    model = YamnetTFLite(model_path)

    print(f"Model   : {model_path}")
    print(f"Classes : {class_map_path}")
    print(f"Input   : {model.in_dtype.__name__}  q={model.in_det['quantization']}")
    print(f"Output  : {model.out_dtype.__name__}  q={model.out_det['quantization']}")

    iterator = tqdm(audio_paths, desc="Infer", unit="file") if len(audio_paths) > 1 and tqdm is not None else audio_paths
    for audio_path in iterator:
        try:
            preds = infer_file(audio_path, model, labels, args.top_k)
            print_predictions(audio_path, preds)
        except Exception as exc:
            print(f"[WARN] {audio_path}: {exc}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
